apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-gumball-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-gumball-service
                port:
                  number: 8080